---
- name: create e-com website
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Pre-requisites
      firewalld:
        service: https
        permanent: yes
        state: enabled
    - name: Deploy and Configure Database
      command: yum install -y mariadb-server
