- name: install flux:v2 cli
  hosts: bastion
  tasks:
    - name: install flux cli
      shell: "curl -s https://raw.githubusercontent.com/fluxcd/flux2/main/install/flux.sh | sudo bash"
    - name: Check prerequisites
      shell: "flux check --pre"
