- name: install flux:v2 cli
  hosts: localhost
  ignore_errors: yes
  tasks:
    - name: install flux cli
      shell: "curl -s https://raw.githubusercontent.com/fluxcd/flux2/main/install/flux.sh | sudo bash"

    - name: install kubectl
      shell: "{{ item }}"
      with_items:
        - "curl -o kucurl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.12/2020-11-02/bin/linux/amd64/kubectlbectl.sha256 https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl.sha256"
        - "chmod +x ./kubectl"
        - "mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin"
        - "echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc"
        - "kubectl version --short --client"
    - name: Check prerequisites
      shell: "flux check --pre"
